### ISSUE TITLE
visualstudio.microsoft.com/zh-hans/ page exception

### ISSUE THREAD

**Issue by HeMinzhang** [MicrosoftDocs/visualstudio-docs.zh-cn#130] opened 2019-07-01 03:33 UTC
> visualstudio.microsoft.com/zh-hans/ Opening is normal, but jumping from other places with the url parameter will generate an exception.
----------------------------------------------------------------------------------------------
**Browser： Chrome 75.0.3770.100**
First open:
https://www.microsoft.com/zh-cn/

click **所有Microsoft** In the right navigation bar ，then click **visual studio** ,

![QQ截图20190701111719](https://user-images.githubusercontent.com/2683269/60408664-73e09600-9bf2-11e9-8b65-01222ee4bd90.png)

Will jump to
**https://visualstudio.microsoft.com/zh-hans/?rr=https%3A%2F%2Fwww.microsoft.com%2Fzh-cn%2F**

some exception will be found on the page

![QQ截图20190701111748](https://user-images.githubusercontent.com/2683269/60408788-efdade00-9bf2-11e9-8f59-7d0052911bba.png)

1. url error parameters
2. Browser console error prompt （have been repaired these days）
3. Page error transparency（have been repaired these days）
----------------------------------------------------------------------------------------

**Browser： Chrome 75.0.3770.100**
Normal access https://visualstudio.microsoft.com/zh-hans/ test

![QQ截图20190701111823](https://user-images.githubusercontent.com/2683269/60408831-19940500-9bf3-11e9-8f28-c3ad66ad5781.png)

-----------------------------------------------------------------------------------------------------

**Browser：Microsoft Edge 44.18362.1.0 and Microsoft EdgeHTML 18.18362**
**Browser: Internet Explorer 11.175.18362.0**
Microsoft edge and ie browser test completed normally,jump to https://visualstudio.microsoft.com/ from https://www.microsoft.com/zh-cn/

![QQ截图20190701113052](https://user-images.githubusercontent.com/2683269/60408946-b656a280-9bf3-11e9-92da-f79c09d384dd.png)

**Comment by CeciAc** [comment] 2019-07-01 17:46
Hello, @HeMinzhang 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment] 2019-07-17 21:35
@JasonCard we cannot repro the error here, can you please check this?

**Comment by JasonCard** [comment] 2019-07-17 23:11
@CeciAc I also tried using the latest version of Chrome and selected Simplified Chinese as language for both sites, but did not repro the "Failed to load resource" errors in screenshot.

**Comment by HeMinzhang** [comment] 2019-07-18 03:00
> Still have url error parameters

![QQ截图20190718105830](https://user-images.githubusercontent.com/2683269/61425942-2f236180-a94b-11e9-995e-9005cee54378.png)
![QQ截图20190718105905](https://user-images.githubusercontent.com/2683269/61425945-334f7f00-a94b-11e9-89bf-b92361d4923f.png)

**Comment by HeMinzhang** [comment] 2019-07-18 03:01
![QQ截图20190718110108](https://user-images.githubusercontent.com/2683269/61425984-5c700f80-a94b-11e9-9319-21f2723d7196.png)

**Comment by JasonCard** [comment] 2019-07-18 03:14
@HeMinzhang Thank you for the additional screenshots for clarification. 
@CeciAc I can repro the URL issue and messages below (to repro, you will need to set the language of site [https://visualstudio.microsoft.com](https://visualstudio.microsoft.com) to Simplified Chinese:   
- *A preload for 'https://c.s-microsoft.com/static/fonts/segoe-ui/west-european/normal/latest.woff2' is found, but is not used because the request credentials mode does not match. Consider taking a look at crossorigin attribute.*
- *The resource https://c.s-microsoft.com/static/fonts/segoe-ui/west-european/normal/latest.woff2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.*

**Comment by HeMinzhang** [comment] 2019-07-18 03:41
I may have known the url parameters. 
**in https://visualstudio.microsoft.com** The Chinese language of the webpage includes zh-hans and zh-hant. 
So not a problem.

**Comment by HeMinzhang** [comment] 2019-07-18 03:44
![QQ截图20190718114243](https://user-images.githubusercontent.com/2683269/61427585-4d8c5b80-a951-11e9-9045-c1d9962f0b43.png)

> https://visualstudio.microsoft.com/zh-hans/

![QQ截图20190718114258](https://user-images.githubusercontent.com/2683269/61427587-51b87900-a951-11e9-9d6d-0418bca01d85.png)

**https://visualstudio.microsoft.com/zh-hant/**
![QQ截图20190718114310](https://user-images.githubusercontent.com/2683269/61427590-55e49680-a951-11e9-8fd4-e27cd955b0a9.png)

**Comment by HeMinzhang** [comment] 2019-07-18 03:49
But I still want to know what the **rr** prompt stands for.
![QQ截图20190718114830](https://user-images.githubusercontent.com/2683269/61427821-1e2a1e80-a952-11e9-8b79-08a17c0ac8ad.png)

**Comment by CeciAc** [comment] 2019-07-24 17:38
Hi @JasonCard @HeMinzhang 
This looks like is fixed now, can you confirm so we can close ths issue?
![imagen](https://user-images.githubusercontent.com/26746247/61815495-bf1c4c00-ae20-11e9-98b3-20c1744c68a4.png)

**Comment by JasonCard** [comment] 2019-07-24 18:15
@CeciAc It looks like it does not repro with Firefox, but it still repro with Chrome and Edge.
Chrome:
![zh-cn_errors](https://user-images.githubusercontent.com/18313964/61817646-db5dc000-ae03-11e9-93b9-3fdd84bdca55.png)
Edge:
![zh-cn_errors_Edge](https://user-images.githubusercontent.com/18313964/61817784-30013b00-ae04-11e9-86e2-2b6c0123202a.png)

**Comment by HeMinzhang** [comment] 2019-07-25 21:15
@JasonCard
As I said before:

normal access  
 https://visualstudio.microsoft.com/zh-hans/ 

Use seem to be wrong parameters
https://visualstudio.microsoft.com/zh-hans/?rr=https%3A%2F%2Fwww.microsoft.com%2Fzh-cn%2F

Maybe two different error tips, I am a bold guess, the parameters cause some operations to cause problems

**Comment by HeMinzhang** [comment] 2019-07-25 21:17
And only special browsers (such as chrome) will generate the wrong parameters.

**Comment by HeMinzhang** [comment] 2019-07-25 21:24
Suggest
1、Compatible parameters, different browsers.
2、Or no parameters（rr=https%3A%2F%2Fwww.microsoft.com%2Fzh-cn%2F), different browsers.

**Comment by JasonCard** [comment] 2019-07-25 21:25
@HeMinzhang cc @CeciAc Yes, we can repro the issue and currently in the process of escalating to appropriate team to investigate further.

**Comment by JasonCard** [comment] 2021-01-29 21:50
@HeMinzhang We're sorry for the long delay on this, but just confirmed that this issue is resolved.

**Closed by JasonCard** 2021-01-29 21:50 UTC
Labels: Technical Issue
